### ISSUE TITLE
i dont't get it

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [fnando/vscode-linter#22]
- Do i replace Stylelint extension?
- Does it read my .Stylelintrc
- How run it and get the output (npx run linter ?)
- How to make it work with Prettier ?

**Comment by fnando** [comment]
> Do i replace Stylelint extension?

That's the idea. Instead of installing one extension for each language, you'd install just this one. It's possible it won't be as feature complete as the other, but it's been working for me.

> Does it read my .Stylelintrc

Yes, configuration is solely made by using linter's configuration files. You can see some debug info on Output > linter: it shows the command that's being executed, which configuration file was found, etc.

> How run it and get the output (npx run linter ?)

This extension doesn't provide any external tool for running linters. That means you have to do whatever you're doing now (e.g. package.json's scripts section).

> How to make it work with Prettier ?

If you have Prettier set up on your environment (it uses $PATH to detect the `prettier` command), it should work. Take a look at Output > linter for debugging info.
